server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms-route # 商品管理路由
          uri: lb://service-pms
          predicates:
            - Path=/pms/**
        - id: oms-route # 订单管理路由
          uri: lb://service-oms
          predicates:
            - Path=/oms/**
        - id: ums-route # 用户管理路由
          uri: lb://service-ums
          predicates:
            - Path=/ums/**
        - id: wms-route # 仓库管理路由
          uri: lb://service-wms
          predicates:
            - Path=/wms/**
        - id: sms-route # 营销管理路由
          uri: lb://service-sms
          predicates:
            - Path=/sms/**

      globalcors:
        corsConfigurations:
          '[/**]':
            #设置允许访问携带cookie的
            allowCredentials: true
            #可以填写多个域名用","隔开 例如："http://www.xiaolc.cn,https://spring.io"  "*"代表允许所有
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


